### ISSUE TITLE
Do not add the middleware outside of dev/test mode

### ISSUE THREAD

**Issue by eric-burel** [cypress-io/cypress-mock-ssr#3]
Hi, coming from Next.js testing discussion (https://github.com/vercel/next.js/discussions/28173#discussioncomment-1391559). Haven't tested the code yet, but I have a small remark regarding the readme.

Currently, the solution is "invasive", as it requires to add a middleware in the existing server. It frightens dev, because one more middleware = one more point of failure and point of entry for attackers. I am really extra careful whenever adding any kind of middleware to my server.

The solution might be as simple as adding this to the README code samples:
```js
// To test your Next.js app with Cypress, remember to start it in development or with NODE_ENV="test"
if (["development", "test"].includes(process.env.NODE_ENV)) {
    // add the middleware
}
```

Next.js will probably also support custom environments in the future, that would make it possible to also add "staging" to the list for example (RFC https://github.com/vercel/next.js/discussions/25764).

**Comment by kevinold** [comment]
Add clarification for use with Next.js de67dfaa9fd0a88224fd723b9d07feb227db613d
