### ISSUE TITLE
Do not advise to use a custom server in Next.js

### ISSUE THREAD

**Issue by eric-burel** [cypress-io/cypress-mock-ssr#4]
Second issue I notice about Next.js in the README: you advise users to create a custom server. The problem is that it's an anti-pattern that leaves you out of Next.js pit of success. I understand that it's tempting, the underlying issue is that Next currently expose no way to add a custom middleware to their internal server, which leads to all sort of limitations in Next.js app (eg people using `getServerSideProps` just to check auth, which lead to a suboptimal experience).

The readme requires, at least, a warning that a custom server is an advanced feature. Imo the right solution in the long run would be to run an additional proxy server in front of Next.js (but that's kinda beyond my current skillset :)).

**Comment by kevinold** [comment]
Add clarification for use with Next.js de67dfa
